s1 = str(input('nhập chuỗi s1:'))
s2 = str(input('nhập chuỗi s2:'))
s3 = str(input('nhập chuỗi s3:'))
index = int(input('nhập index:'))
print('chiều dài của các chuỗi s1, s2 và s3 lần lượt là:',len(s1),len(s2),len(s3))
print('chuỗi s4:',s1[index:])
print('chuỗi s2 lặp lại 2 lần:',s2*2)